# Thank you for Downloading InvisibleItemFrames!
#
# Feel free to check out my other plugins here:
# https://www.spigotmc.org/members/429752/#resources

Messages:

  Only Players: "&c此指令只能由玩家輸入。"
  
  No Permission: "&c你沒有權限"

  Toggle: "&a此展示框已被設為 %status%"
  Toggle On: "&2&l正常"
  Toggle Off: "&c&l隱形"

  Toggle Mode: "&a你已 %status%&a 切換模式!"
  Toggle Mode On: "&2&l開啟"
  Toggle Mode Off: "&c&l關閉"
  
  Not Looking: "&c你的遊戲十字準星未對準一個展示框"
  
  Command Usage:
    - "&c展示框控制教學:"
    - "&a/ITF toggle &7- &f將看著的展示框切換為正常/隱形"
    - "&a/ITF togglemode &7- &fEnable/Disable 開啟此模式後，右鍵可將展示框切換成正常/隱形"