# Thank you for Downloading InvisibleItemFrames!
#
# Feel free to check out my other plugins here:
# https://www.spigotmc.org/members/429752/#resources

Messages:

  Only Players: "&c這只能由玩家使用."
  
  No Permission: "&c您沒有權限執行此動作."

  Toggle: "&a您已將此物品展示框切換為 %status%"
  Toggle On: "&2&l可視"
  Toggle Off: "&c&l隱形"

  Toggle Mode: "&a您已 %status%&a 快速切換模式!"
  Toggle Mode On: "&2&l開啟"
  Toggle Mode Off: "&c&l關閉"
  
  Scan: "&aFound %count% item frames."
  Scan No Number: "&cPlease provide a scan radius."
  
  Not Looking: "&cYou're not looking at an Item Frame."
  Non Number: "&c&l%value%&c is not a number or out of range (1-127)"
  
  Command Usage:
    - "&cInvisibleItemFrames Usages:"
    - "&a/ITF toggle &7- &fWhile looking at Item Frame."
    - "&a/ITF togglemode &7- &fEnable/Disable where you can right click Item Frames"
    - "&a/ITF scan (radius) &7- &fScan for Item Frames and spawn some particles at them"