instruments:
    PIANO: "DIRT"
    BASS_GUITAR: "OAK_PLANKS"
    SNARE_DRUM: "SAND"
    STICKS: "GLASS"
    BASS_DRUM: "STONE"
    BELL: "GOLD_BLOCK"
    FLUTE: "CLAY"
    CHIME: "PACKED_ICE"
    GUITAR: "WHITE_WOOL"
    XYLOPHONE: "BONE_BLOCK"
    IRON_XYLOPHONE: "IRON_BLOCK"
    COW_BELL: "SOUL_SAND"
    DIDGERIDOO: "PUMPKIN"
    BIT: "EMERALD_BLOCK"
    BANJO: "HAY_BLOCK"
    PLING: "GLOWSTONE"
# Configure the plugin messages, the message should always include all the %s as
# it's used to paste in information such as instrument names. The messages won't work without them !!!
messages:
    menu-title: "音階盒編輯器"
    second-octave: "(第二個八度)"
    menu-instrument-change-title: "§6§l%s"
    menu-instrument-change-description: "§7設置音階盒聲音為 %s\n§0 \n§e§l左鍵點擊 §7設置\n§e§l右鍵點擊 §7預覽播放"
    menu-note-change-title: "§6§l%s"
    menu-note-change-description: "§7等同於 %s 音符\n§7或 %s 次點擊\n§7音階盒\n§0 \n§e§l左鍵點擊 §7設置\n§e§l右鍵點擊 §7預覽播放"
    menu-note-change-message: "§e音符已設置為 %s"
    menu-give-description: "§6§l音階盒\n§7預設 %s 次點擊\n§0 \n§e點擊獲取！"
    button-close: "§c關閉"
    button-back: "§e返回"
    button-instrument-menu: "§6§l更改樂器\n§7打開選單以更改音階盒的樂器\n§0 \n§e點擊打開"
    no-build-permission: "§c您沒有建造權限！"
    no-build-permission-below: "§c您沒有權限編輯音階盒下面的方塊！"
    not-looking-at-noteblock: "§c您並未對準一個音階盒！"
    not-a-player: "§c此命令必須作為玩家執行！"
    player-not-found: "§c未找到該玩家！"
    invalid-level: "§c無效的等級！必須是1-25之間的數值"
    received-note-block: "§e收到預設音階盒！"
    pre-set-note-block-name: "§f音階盒（%s 次點擊）"
    set-note-not-number: "§c無效的音符！必須是0-24之間的數字"
    set-note-usage: "§c用法：/noteblock sethand <音符>"
    set-note-set: "§e已將音階盒設置為 %s"
    set-note-not-holding: "§c您沒有拿著音階盒！"
    command-no-permission: "§c權限不足：noteblockeditor.command"
    config-reload: "§e重新加載設定檔！"
    config-reload-no-permission: "§c沒有權限重新加載設定檔！"
    general-no-permission: "§c權限不足..."