instruments:
    PIANO: "DIRT"
    BASS_GUITAR: "OAK_PLANKS"
    SNARE_DRUM: "SAND"
    STICKS: "GLASS"
    BASS_DRUM: "STONE"
    BELL: "GOLD_BLOCK"
    FLUTE: "CLAY"
    CHIME: "PACKED_ICE"
    GUITAR: "WHITE_WOOL"
    XYLOPHONE: "BONE_BLOCK"
    IRON_XYLOPHONE: "IRON_BLOCK"
    COW_BELL: "SOUL_SAND"
    DIDGERIDOO: "PUMPKIN"
    BIT: "EMERALD_BLOCK"
    BANJO: "HAY_BLOCK"
    PLING: "GLOWSTONE"
# Configure the plugin messages, the message should always include all the %s as
# it's used to paste in information such as instrument names. The messages won't work without them !!!
messages:
    menu-title: "音階盒"
    second-octave: "(第二個八度)"
    menu-instrument-change-title: "§6§l%s"
    menu-instrument-change-description: "§7將此音階盒\n§7聲音設為 %s\n§0 \n§e§l左鍵§7設定\n§e§l右鍵§7預覽"
    menu-note-change-title: "§6§l%s"
    menu-note-change-description: "§7設為半分音符 %s\n§7或 %s 點擊\n§7音階盒\n§0 \n§e§l左鍵§7設定\n§e§l右鍵§7預覽" 
    menu-note-change-message: "§e音高設為 %s"
    button-close: "§c關閉"
    button-back: "§e返回"
    button-instrument-menu: "§6§l更改樂器\n§7開啟選單來更改音階盒的樂器\n§0 \n§e點擊開啟"
    no-build-permission: "§c您沒有在此建築的權限!"
    no-build-permission-below: "§c你沒有編輯該音階盒底下方塊的權限!"
    not-looking-at-noteblock: "§c你必須看著一個音階盒!"
    not-a-player: "§c此指令只能由玩家運行!"
    command-no-permission: "§c權限不足: noteblockeditor.command"
    config-reload: "§e已重載設定!"
    config-reload-no-permission: "§c沒有重載設定的權限!"